<?php
// $Id: xoops_version.php,v 1.1 2006/03/10 20:06:33 mikhail Exp $

$modversion['name'] = _MI_XOOGLE_NAME;
$modversion['version'] = '0.73';
$modversion['description'] = _MI_XOOGLE_DESC;
$modversion['credits'] = '';
$modversion['author'] = _MI_XOOGLE_AUTHOR;
// $modversion['help'] = 'help.html';
$modversion['license'] = 'see api.google.com';
$modversion['official'] = 0;
$modversion['image'] = 'images/xoogle_logo.png';
$modversion['dirname'] = 'xoogle';

// Admin
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
// $modversion['adminmenu'] = "admin/menu.php";

// Menu
$modversion['hasMain'] = 1;

// Search
$modversion['hasSearch'] = 1;
$modversion['search']['file'] = 'include/xoogle.php';
$modversion['search']['func'] = 'xoopsXoogleSearch';

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// Xoogle  0.7.3  uses sql file 0.7.2
$modversion['sqlfile']['mysql'] = 'sql/xoogle_0.7.2.sql';

// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'xoogle_config';
// $modversion['tables'][1] = 'xoogle_saved';

// Templates
$modversion['templates'][1]['file'] = 'xoogle.html';
$modversion['templates'][1]['description'] = 'xoogle main template';

$modversion['templates'][2]['file'] = 'xoogle_form.html';
$modversion['templates'][2]['description'] = 'xoogle form template';

$modversion['templates'][3]['file'] = 'xoogle_paginate.html';
$modversion['templates'][3]['description'] = 'xoogle paginate template';

// Blocks
$modversion['blocks'][1]['file'] = 'xoogle_search_block.php';
$modversion['blocks'][1]['name'] = _MI_SEARCH_BLOCK_NAME;
$modversion['blocks'][1]['description'] = _MI_SEARCH_BLOCK_DESC;
$modversion['blocks'][1]['show_func'] = 'XoogleBlockSearch';
$modversion['blocks'][1]['template'] = 'search_block.html';

